services:
  mysql:
    image: mysql:8.4
    container_name: pizza_delivery_mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: pizza_delivery_mysql
    ports:
      - "3306:3306"
    volumes:
      - pizza_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pizza_mysql_data:
