import { sequelize } from './config/db.js';

async function fixTables() {
  try {
    await sequelize.authenticate();
    
    const tables = ['users', 'pizzas', 'orders', 'coupons', 'carts', 'cartitems', 'orderitems'];
    
    for (const table of tables) {
      try {
        console.log(`Checking table: ${table}`);
        
        // 1. Rename capitalized tables to lowercase if they exist and lowercase doesn't
        // (Postgres usually stores them lowercase unless quoted, but Sequelize might have quoted them)
        // Actually, let's just ensure they exist and have identity.
        
        const [result] = await sequelize.query(`
          SELECT column_name, data_type 
          FROM information_schema.columns 
          WHERE table_schema = 'public' AND table_name = '${table}' AND column_name = 'id';
        `);
        
        if (result.length > 0) {
          console.log(`Table ${table} exists. Ensuring identity on id...`);
          try {
            await sequelize.query(`ALTER TABLE public.${table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;`).catch(e => console.log(`Identity already exists or error on ${table}: ${e.message}`));
          } catch (e) {}
        } else {
          console.log(`Table ${table} does NOT exist or has no id column.`);
        }
      } catch (err) {
        console.error(`Error processing table ${table}:`, err.message);
      }
    }
    
    console.log("Database fix complete.");
  } catch (err) {
    console.error("Connection error:", err);
  } finally {
    await sequelize.close();
  }
}

fixTables();
